// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Flock
	{
		// forces
		float separate, align, cohesion;
		float disSep, disAlign, distCohe;
		float maxTurn, maxSpeed, maxForce;

		// bounds
		float minX, minY, maxX, maxY, boundsWidth, boundsHeight;
		int boundmode;

		// new
		float dt; // not sure what's this yet
		float attraction, attractionDeviation;

		public Flock ()
		{
			separate = align = cohesion = disSep = disAlign = distCohe = 
				maxTurn = maxSpeed = maxForce = minX = minY = maxX = maxY = 
					boundsWidth = boundsHeight = 0;
			boundmode = 0;
			dt = 1.0f;
			attraction = attractionDeviation = 0.0f;
		}
	}


}

